services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - ./upload:/var/www/html/storage/upload
      - ./database:/var/www/html/storage/database
    env_file: .env
    networks:
      - caddy_proxy
    #ports:
    #  - 80:8080

networks:
  caddy_proxy:
    external: true