services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - ./local_upload:/var/www/html/storage/upload
      - ./local_database:/var/www/html/storage/database
    env_file: .env
    networks:
      - caddy_proxy
    #ports:
    #  - 80:8080

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    container_name: firefly_iii_importer
    restart: always
    networks:
      - caddy_proxy
    #ports:
    #  - "8081:8080"
    env_file: .env
networks:
  caddy_proxy:
    external: true