# ~/homelab/services/olivetin/config.yaml

logLevel: "INFO"
logFormat: "text"
themeName: linen-lab

listenAddressSingleHTTPFrontend: "0.0.0.0:1337"
entities:
  - file: /etc/OliveTin/docker_entities.yaml
    name: docker_entities

actions:
  - title: Container Tools
    shell: 'docker compose -f {{ Container }}/compose.yml {{ Action }}'
    icon: <iconify-icon icon="uil:docker" width="24" height="24"></iconify-icon>
    popupOnStart: execution-dialog
    timeout: 120
    arguments:
      - name: Container
        entity: docker_entities
        title: 'Select Package'
        choices:
          - value: '{{ docker_entities.location }}'
            title: '{{ docker_entities.name }}'
      - name: Action
        title: 'Action'
        choices:
          - title: Start
            value: start
          - title: Stop
            value: stop
          - title: Restart
            value: restart
          - title: Events
            value: events
          - title: Down
            value: down
          - title: Up
            value: "up -d"
          - title: Build
            value: "up -d --build"

  - title: Up {{docker_entities.name}}
    icon: box
    shell: docker compose -f {{docker_entities.location}}/compose.yml up -d
    entity: docker_entities

  - title: Down {{docker_entities.name}}
    icon: box
    shell: docker compose -f {{docker_entities.location}}/compose.yml down
    entity: docker_entities




  # Git
  - title: "Git: Pull homelab repo"
    icon: <iconify-icon icon="mdi:github" width="24" height="24"></iconify-icon>
    shell: git -C /root/homelab pull
    timeout: 30

  - title: "Git: Pull homelab repo (Force)"
    icon: <iconify-icon icon="mdi:github" width="24" height="24"></iconify-icon>
    shell: |
      git -C /root/homelab fetch --all
      git -C /root/homelab reset --hard origin/main
    timeout: 60
    description: "Force pull latest main, discarding all local changes"

  - title: "OliveTin: Restart"
    icon: <iconify-icon icon="openmoji:olive" width="72" height="72"></iconify-icon>
    shell: |
      rm -r /etc/OliveTin
      ln -s /root/homelab/services/olivetin /etc/OliveTin
      systemctl restart OliveTin
    timeout: 15
    description: "Reload OliveTin config after changes"

dashboards:
  # This is the second dashboard.
  - title: My Containers
    contents:
      - title: 'Container {{ docker_entities.name }}' # ({{ docker_entities.image }})'
        entity: docker_entities
        type: fieldset
        contents:
          - title: 'Start {{ docker_entities.name }}'
          - title: 'Stop {{ docker_entities.name }}'
