# ~/homelab/services/olivetin/config.yaml

logLevel: "INFO"
logFormat: "text"
themeName: linen-lab

listenAddressSingleHTTPFrontend: "0.0.0.0:1337"
entities:
  - file: /etc/OliveTin/docker_entities.yaml
    name: docker_entities

actions:
  - title: Container Tools
    shell: 'docker compose -f {{ Container }}/compose.yml {{ Action }}'
    icon: <iconify-icon icon="uil:docker" width="24" height="24"></iconify-icon>
    popupOnStart: execution-dialog
    timeout: 120
    arguments:
      - name: Container
        entity: docker_entities
        title: 'Select Package'
        choices:
          - value: '{{ docker_entities.location }}'
            title: '{{ docker_entities.name }}'
      - name: Action
        title: 'Action'
        choices:
          - title: Start
            value: start
          - title: Stop
            value: stop
          - title: Restart
            value: restart
          - title: Events
            value: events
          - title: Down
            value: down
          - title: Up
            value: "up -d"
          - title: Build
            value: "up -d --build"

  - title: Up {{ docker_entities.name }}
    icon: <iconify-icon icon="ic:baseline-play-circle" width="72" height="72"></iconify-icon>
    shell: docker compose -f {{ docker_entities.location }}/compose.yml up -d
    entity: docker_entities
    
  - title: Down {{ docker_entities.name }}
    icon: <iconify-icon icon="ic:baseline-stop-circle" width="72" height="72"></iconify-icon>
    shell: docker compose -f {{ docker_entities.location }}/compose.yml down
    entity: docker_entities

  - title: Restart {{ docker_entities.name }}
    icon: <iconify-icon icon="ic:baseline-refresh" width="72" height="72"></iconify-icon>
    shell: docker compose -f {{ docker_entities.location }}/compose.yml restart
    entity: docker_entities

  - title: Logs {{ docker_entities.name }}
    icon: <iconify-icon icon="ic:baseline-description" width="72" height="72"></iconify-icon>
    shell: docker compose -f {{ docker_entities.location }}/compose.yml logs -f
    entity: docker_entities
    popupOnStart: execution-dialog
    timeout: 300

  - title: Pull {{ docker_entities.name }}
    icon: <iconify-icon icon="ic:baseline-download" width="72" height="72"></iconify-icon>
    shell: docker compose -f {{ docker_entities.location }}/compose.yml pull
    entity: docker_entities
    popupOnStart: execution-dialog
    timeout: 300

  - title: "VPN Containers: Start"
    icon: <iconify-icon icon="ic:baseline-play-circle" width="72" height="72"></iconify-icon>
    shell: virsh start vpn-containers

  - title: "VPN Containers: Shutdown"
    icon: <iconify-icon icon="ic:baseline-power-settings-new" width="72" height="72"></iconify-icon>
    shell: virsh shutdown vpn-containers

  - title: "VPN Containers: Reboot"
    icon: <iconify-icon icon="ic:baseline-refresh" width="72" height="72"></iconify-icon>
    shell: virsh reboot vpn-containers

  - title: "VPN Containers: Destroy"
    icon: <iconify-icon icon="ic:baseline-stop-circle" width="72" height="72"></iconify-icon>
    shell: virsh destroy vpn-containers

  - title: "VPN Containers: Status"
    icon: <iconify-icon icon="ic:baseline-info" width="72" height="72"></iconify-icon>
    shell: virsh dominfo vpn-containers
    popupOnStart: execution-dialog
    timeout: 30

#docker inspect --format "{{.State.Health.Status}}" $(docker compose ps -q)   


  # Git
  - title: "Git: Pull homelab repo"
    icon: <iconify-icon icon="mdi:github" width="24" height="24"></iconify-icon>
    shell: git -C /root/homelab pull
    timeout: 30

  - title: "Git: Pull homelab repo (Force)"
    icon: <iconify-icon icon="mdi:github" width="24" height="24"></iconify-icon>
    shell: |
      git -C /root/homelab fetch --all
      git -C /root/homelab reset --hard origin/main
    timeout: 60
    description: "Force pull latest main, discarding all local changes"

  # Olivetin
  - Title: "Olivetin: Update"
    icon: <iconify-icon icon="openmoji:olive" width="72" height="72"></iconify-icon>
    shell: |
      wget https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin_linux_amd64.deb
      dpkg -i OliveTin_linux_amd64.deb
      rm OliveTin_linux_amd64.deb
      systemctl restart OliveTin
    timeout: 60
    description: "Update OliveTin to the latest version and restart the service"

  - title: "OliveTin: Restart"
    icon: <iconify-icon icon="openmoji:olive" width="72" height="72"></iconify-icon>
    shell: |
      rm -r /etc/OliveTin
      ln -s /root/homelab/services/olivetin /etc/OliveTin
      systemctl restart OliveTin
    timeout: 15
    description: "Reload OliveTin config after changes"

dashboards:
  - title: This Server
    contents:
      - title: Container Tools
      - title: "Git: Pull homelab repo"
      - title: "Git: Pull homelab repo (Force)"
      - title: "OliveTin: Restart"
      - title: "Olivetin: Update"


  # This is the second dashboard.
  - title: My Containers
    contents:
      - title: 'Container {{ docker_entities.name }}' # ({{ docker_entities.image }})'
        entity: docker_entities
        type: fieldset
        contents:
          - title: 'Up {{ docker_entities.name }}'
          - title: 'Down {{ docker_entities.name }}'
          - title: 'Restart {{ docker_entities.name }}'
          - title: 'Logs {{ docker_entities.name }}'
          - title: 'Pull {{ docker_entities.name }}'

  - title: VMS
    contents:
      - title: 'VPN Containers: Start'
      - title: 'VPN Containers: Shutdown'
      - title: 'VPN Containers: Reboot'
      - title: 'VPN Containers: Destroy'
      - title: 'VPN Containers: Status'

