services:
  clipboard:
    build: .
    container_name: linen_clipboard
    restart: unless-stopped
    #ports:
    #  - "8090:5000"
    volumes:
      - ./local_data:/data
    environment:
      - DATA_DIR=/data
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true
