services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      #- 8096:8096/tcp
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ./local-config:/config
      - ./local-cache:/cache
      - /mnt/storage/Video/Shows:/data/tvshows
      - /mnt/storage/Video/Movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true