services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./local_ollama_data:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    networks:
      - caddy_proxy
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_IGPU_ENABLE=1

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    #ports:
    #  - "3000:8080"
    env_file:
      - .env
    volumes:
      - ./local_open-webui_data:/app/data
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true